//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransPortClientes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitudes_Transporte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Solicitudes_Transporte()
        {
            this.Solicitudes_Transporte_Detalle = new HashSet<Solicitudes_Transporte_Detalle>();
        }
    
        public int id_solicitudes_transporte { get; set; }
        public int id_estado_solicitud { get; set; }
        public Nullable<int> id_piloto { get; set; }
        public int id_cliente { get; set; }
        public int id_punto_origen { get; set; }
        public int id_punto_destino { get; set; }
        public bool activo { get; set; }
        public bool eliminado { get; set; }
        public int id_usuario_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Pilotos Pilotos { get; set; }
        public virtual Puntos Puntos { get; set; }
        public virtual Puntos Puntos1 { get; set; }
        public virtual Solicitud_Estado Solicitud_Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitudes_Transporte_Detalle> Solicitudes_Transporte_Detalle { get; set; }
    }
}
