//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransPortClientes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TransPortEntities : DbContext
    {
        public TransPortEntities()
            : base("name=TransPortEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuarios_Externos> Usuarios_Externos { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Pilotos> Pilotos { get; set; }
        public virtual DbSet<Puntos> Puntos { get; set; }
        public virtual DbSet<Solicitud_Estado> Solicitud_Estado { get; set; }
        public virtual DbSet<Solicitudes_Transporte> Solicitudes_Transporte { get; set; }
        public virtual DbSet<Solicitudes_Transporte_Detalle> Solicitudes_Transporte_Detalle { get; set; }
    }
}
