//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransPortClientes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios_Externos
    {
        public int id_usuario_externo { get; set; }
        public string nombre_usuario { get; set; }
        public string nombre_completo { get; set; }
        public int id_cliente { get; set; }
        public bool activo { get; set; }
        public Nullable<bool> eliminado { get; set; }
        public int id_usuario_creacion { get; set; }
        public Nullable<int> id_usuario_modificacion { get; set; }
        public Nullable<int> id_usuario_eliminacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacio { get; set; }
        public Nullable<System.DateTime> fecha_eliminacion { get; set; }
        public string password { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
